on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test SqlBulkTools.NetStandard.UnitTests --configuration Release --no-build